
import Services from '@/components/services';
import Head from 'next/head';


import Team from '@/components/team';

import About from '../components/about';
import Form from '../components/form';

import Footer from '@/components/footer';
import Hero from '@/components/hero';
import Project from '@/components/project';

const HomePage = () => {
  

  return (
    <>
      <Head>
        <title>Geo-Consultancy Real Estate </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero
          address="225 S 1st St Brooklyn, NY 11211"
          phone="(929) 123-4567"
          email="constrctr@restate.com"
        />

        <About
          cardTitle1="10 years"
          cardSubText1="in business"
          cardTitle2="20-500 Million fcfa"
          cardSubText2="turnover"
          cardTitle3="1000"
          cardSubText3="transactions"
        />
      
        <Team/>
      
        <Services />
        <Project/>
        {/* <Deals /> */}
        {/* <Review /> */}
        {/* <Insta /> */}
        <Form />
        
      </div>
    </>
  );
};

export default HomePage;
